# Generated by Django 5.1.1 on 2024-09-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Email_Subject', models.TextField(max_length=255)),
                ('Email_Date', models.DateTimeField()),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
        ),
    ]
